Fix etree import
This commit fixes the following error:

 File "site-packages/mdlightbox.py", line 10, in <module>
      from markdown.util import etree
 ImportError: cannot import name 'etree' from 'markdown.util' (site-packages/markdown/util.py)

This import is deprecated and should be replaced by import
`xml.etree.ElementTree as etree`.